# Generated by Django 5.0.4 on 2024-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество в чеке'),
            preserve_default=False,
        ),
    ]
