# Generated by Django 5.0.4 on 2024-04-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_remove_checkmodel_item'),
        ('product', '0002_remove_productmodel_name_productmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='check_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='check.checkmodel', verbose_name='Чек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.categorymodel', verbose_name='Категория'),
        ),
    ]
