# Generated by Django 5.0.4 on 2024-04-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productmodel_check_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_id',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='ID Товара'),
            preserve_default=False,
        ),
    ]
