# Generated by Django 5.0.4 on 2024-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAnalyticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField()),
                ('place', models.CharField(max_length=255)),
                ('total_purchases', models.PositiveIntegerField()),
                ('average_receipt', models.FloatField()),
                ('taxes_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_nds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tips', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Аналитика по местам покупки',
                'verbose_name_plural': 'Аналитики по местам покупки',
                'db_table': 'analytic_place_analytic',
            },
        ),
    ]
