# Generated by Django 5.0.4 on 2024-04-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAnalyticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_receipt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Аналитика по категориям',
                'verbose_name_plural': 'Аналитики по категориям',
                'db_table': 'analytic_category_analytic',
            },
        ),
        migrations.RenameField(
            model_name='placeanalyticmodel',
            old_name='place',
            new_name='place_name',
        ),
    ]
