# Generated by Django 5.0.4 on 2024-04-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0002_categoryanalyticmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryanalyticmodel',
            old_name='category',
            new_name='name',
        ),
    ]
