# Generated by Django 5.0.4 on 2024-04-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkmodel',
            name='item',
        ),
    ]
