# Generated by Django 5.0.4 on 2024-04-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_remove_checkmodel_item'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmodel',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='store.storemodel'),
        ),
    ]
